apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: # Provide a name for your system
spec:
  serviceAccountName: batch-job-sa
  nodeSelector:
    kubernetes.io/hostname: fe-na-dev-agent-1
  entrypoint: main
  arguments:
    parameters:
      - name: repoUrl
        value: "" # Put in your repo URL
      - name: repoBranch
        value: "" # Put in the branch you want to deploy
      # Node Selector will be dynamically added by FluxEdge
  templates:
  - name: main
    steps:
      - - name: clone-repo
          template: clone-repo
          arguments:
            parameters:
              - name: repoUrl
                value: "{{workflow.parameters.repoUrl}}"
              - name: repoBranch
                value: "{{workflow.parameters.repoBranch}}"

      - - name: kustomize-build
          template: kustomize-build
          arguments:
            parameters:
              - name: nodeSelector
                value: "{{workflow.parameters.nodeSelector}}"
            artifacts:
              - name: repo
                from: "{{steps.clone-repo.outputs.artifacts.repo}}"

      - - name: apply-kubectl
          template: apply-kubectl
          arguments:
            artifacts:
              - name: manifests
                from: "{{steps.kustomize-build.outputs.artifacts.manifests}}"

  - name: clone-repo
    inputs:
      parameters:
        - name: repoUrl
        - name: repoBranch
    container:
      image: alpine/git
      command: [sh, -c]
      args: [
        "mkdir -p ~/.ssh && cp /secret/ssh-privatekey ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa && \
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts && \
        git clone --branch {{inputs.parameters.repoBranch}} {{inputs.parameters.repoUrl}} /workspace && \
        ls /workspace"
      ]
      volumeMounts:
        - name: ssh-key
          mountPath: /secret
          readOnly: true
    volumes:
      - name: ssh-key
        secret:
          secretName: git-ssh-key # This will need to be updated based on the secret that gets created
    outputs:
      artifacts:
        - name: repo
          path: /workspace

  - name: kustomize-build
    inputs:
      parameters:
        - name: nodeSelector
      artifacts:
        - name: repo
          path: /workspace
    script:
      image: line/kubectl-kustomize
      command: [sh]
      source: |
        #!/bin/sh
        cd /workspace/dev/overlay/dev
        # Replace placeholders in kustomization.yaml with actual values
        sed -i "s/\NODE_SELECTOR/{{inputs.parameters.nodeSelector}}/g" deployment-patch.yaml 
        
        # Generate the manifests using kustomize
        kustomize build . -o /workspace/modified

        ls /workspace/modified
    outputs:
      artifacts:
        - name: manifests
          path: /workspace/modified

  - name: apply-kubectl
    inputs:
      artifacts:
        - name: manifests
          path: /workspace/modified
    container:
      image: bitnami/kubectl:1.21 
      command: [sh, -c]
      args: ["kubectl apply -f /workspace/modified"]